name: build and push Docker image

on:
  push:
    pull_request:
      paths:  # This action will only run if the PR modifies a file in one of these directories
        - 'ml-agents/**'
        - 'ml-agents-envs/**'
        - 'gym-unity/**'
        - 'test_constraints*.txt'
        - 'test_requirements.txt'
      push:
        branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build --tag ml-agents:${GITHUB_SHA} .
